#!/bin/bash -eu
cd "$(dirname "$0")"

for task in snmp cacti librenms nagios nfsen rancid smokeping prometheus grafana syslog netbox; do
  echo "==== $task ====" 
  sudo $task || echo "FAILED: $?"
done
