#!/bin/bash -eux
set -o pipefail
cd "$(dirname "$0")"

systemctl enable postgresql redis-server netbox netbox-rq
systemctl start postgresql redis-server netbox netbox-rq

# Populate the Netbox database
source /opt/netbox/venv/bin/activate
python3 /opt/netbox/netbox/manage.py nbshell <populate.py
deactivate ""
