#!/bin/bash -eux
set -o pipefail
cd "$(dirname "$0")"

# This makes snmpd less verbose in syslog
sed -i 's/-Lsd/-LSwd/' /etc/default/snmpd

cp snmp.conf /etc/snmp/snmp.conf
cp snmpd.conf /etc/snmp/snmpd.conf

if ! grep "^rwuser admin" /usr/share/snmp/snmpd.conf; then
  systemctl stop snmpd || true
  net-snmp-create-v3-user -X AES -a SHA -A NetManage admin || true
fi

systemctl enable snmpd
systemctl restart snmpd
