#!/bin/bash -eux
set -o pipefail
cd "$(dirname "$0")"

# This makes snmpd less verbose in syslog
mkdir -p /etc/systemd/system/snmpd.service.d
(
cat <<EOS
[Service]
ExecStart=
EOS
grep ^ExecStart= /lib/systemd/system/snmpd.service | sed -e 's/ -L[^ ]*/ -LSwd/'
) >/etc/systemd/system/snmpd.service.d/override.conf

cp snmp.conf /etc/snmp/snmp.conf
cp snmpd.conf /etc/snmp/snmpd.conf

if ! grep "^rwuser admin" /usr/share/snmp/snmpd.conf; then
  systemctl stop snmpd || true
  net-snmp-create-v3-user -X AES -a SHA -A NetManage admin || true
fi

systemctl enable snmpd
systemctl restart snmpd
