{
 "title": "SNMP Device Summary",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(ifOperStatus, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Down",
   "type": "singlestat",
   "description": "Number of interfaces with ifOperState 0 and ifAdminState 1",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ifOperStatus{instance=\"$instance\"} != 1 and ifAdminStatus{instance=\"$instance\"} == 1)"
    }
   ]
  },
  {
   "title": "Up",
   "type": "singlestat",
   "description": "Number of interfaces with ifOperState 1",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ifOperStatus{instance=\"$instance\"} == 1)"
    }
   ]
  },
  {
   "title": "Top 5 interfaces",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, irate(ifHCInOctets{instance=\"$instance\"}[5m]) or irate(ifInOctets{instance=\"$instance\"}[5m]) or irate(ifHCOutOctets{instance=\"$instance\"}[5m]) or irate(ifOutOctets{instance=\"$instance\"}[5m]))*8",
     "legendFormat": "{{ ifName }}"
    }
   ]
  },
  {
   "title": "Traffic (all interfaces)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(irate(ifHCInOctets{instance=\"$instance\"}[2m]) or irate(ifInOctets{instance=\"$instance\"}[2m]))*8",
     "legendFormat": "IN: {{ifName}} {{ifAlias}}"
    },
    {
     "expr": "(irate(ifHCOutOctets{instance=\"$instance\"}[2m]) or irate(ifOutOctets{instance=\"$instance\"}[2m]))*8",
     "legendFormat": "OUT: {{ifName}} {{ifAlias}}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "ifPhysAddress" }
   ]
  }
 ]
}