#!/bin/bash -eux
set -o pipefail
cd "$(dirname "$0")"

cp Alerts General Probes /etc/smokeping/config.d/

./Targets.${LANGUAGE_TAG:-en}.sh > /etc/smokeping/config.d/Targets

systemctl enable smokeping
systemctl restart smokeping
