#!/bin/bash -eux
set -o pipefail
cd "$(dirname "$0")"

GENERIC_DEVICE_TEMPLATE="$(/usr/share/cacti/cli/add_device.php --list-host-templates | grep -m1 "Generic SNMP Device" | awk '{print $1}')"
LINUX_DEVICE_TEMPLATE="$(/usr/share/cacti/cli/add_device.php --list-host-templates | grep -m1 "Net-SNMP Device" | awk '{print $1}')"
CISCO_DEVICE_TEMPLATE="$(/usr/share/cacti/cli/add_device.php --list-host-templates | grep -m1 "Cisco Router" | awk '{print $1}')"

GRAPH_TEMPLATE="$(/usr/share/cacti/cli/add_graphs.php --list-graph-templates | grep -m1 "Interface - Traffic (bits/sec)" | awk '{print $1}')"
SNMP_QUERY="$(/usr/share/cacti/cli/add_graphs.php --list-snmp-queries | grep -m1 "SNMP - Interface Statistics" | awk '{print $1}')"
QUERY_TYPE="$(/usr/share/cacti/cli/add_graphs.php --list-query-types --snmp-query-id="$SNMP_QUERY" | grep -m1 "In/Out Bits (64-bit Counters)$" | awk '{print $1}')"

add () {
  host="$1"
  device_template_id="$2"

  res="$(/usr/share/cacti/cli/add_device.php --description="$host" \
    --ip="$host" --version=2 --community=NetManage --template="$device_template_id" || true)"
  echo "$host: $res"
  id="$(expr "$res" : '.*device-id: (\([0-9][0-9]*\))')"
  [ -n "$id" ] || return
  iftype="$(/usr/share/cacti/cli/add_graphs.php --list-snmp-values --host-id="$id" --snmp-query-id="$SNMP_QUERY" --snmp-field=ifType --snmp-value-regex=Ethernet | grep -m1 ethernetCsmacd || true)"
  [ -n "$iftype" ] && /usr/share/cacti/cli/add_graphs.php --host-id="$id" --graph-type=ds --graph-template-id="$GRAPH_TEMPLATE" \
      --snmp-query-id="$SNMP_QUERY" --snmp-query-type-id="$QUERY_TYPE" --snmp-field=ifType --snmp-value="$iftype" || true
  true
}

add noc.ws.nsrc.org $LINUX_DEVICE_TEMPLATE
add gw.ws.nsrc.org $LINUX_DEVICE_TEMPLATE
add transit1.nren.ws.nsrc.org $CISCO_DEVICE_TEMPLATE
add transit2.nren.ws.nsrc.org $CISCO_DEVICE_TEMPLATE
