- labels:
    module: ping4
  targets:
    - 1.2.3.4
    - nsrc.org
    - gw.ws.nsrc.org
    - sw.ws.nsrc.org

- labels:
    module: ping6
  targets:
    - bdr1.campus1.ws.nsrc.org
    - bdr1.campus2.ws.nsrc.org
    - bdr1.campus3.ws.nsrc.org
    - bdr1.campus4.ws.nsrc.org
    - bdr1.campus5.ws.nsrc.org
    - bdr1.campus6.ws.nsrc.org
    - core1.campus1.ws.nsrc.org
    - core1.campus2.ws.nsrc.org
    - core1.campus3.ws.nsrc.org
    - core1.campus4.ws.nsrc.org
    - core1.campus5.ws.nsrc.org
    - core1.campus6.ws.nsrc.org
    - dist1-b1.campus1.ws.nsrc.org
    - dist1-b1.campus2.ws.nsrc.org
    - dist1-b1.campus3.ws.nsrc.org
    - dist1-b1.campus4.ws.nsrc.org
    - dist1-b1.campus5.ws.nsrc.org
    - dist1-b1.campus6.ws.nsrc.org
    - dist1-b2.campus1.ws.nsrc.org
    - dist1-b2.campus2.ws.nsrc.org
    - dist1-b2.campus3.ws.nsrc.org
    - dist1-b2.campus4.ws.nsrc.org
    - dist1-b2.campus5.ws.nsrc.org
    - dist1-b2.campus6.ws.nsrc.org
    - edge1-b1.campus1.ws.nsrc.org
    - edge1-b1.campus2.ws.nsrc.org
    - edge1-b1.campus3.ws.nsrc.org
    - edge1-b1.campus4.ws.nsrc.org
    - edge1-b1.campus5.ws.nsrc.org
    - edge1-b1.campus6.ws.nsrc.org
    - edge1-b2.campus1.ws.nsrc.org
    - edge1-b2.campus2.ws.nsrc.org
    - edge1-b2.campus3.ws.nsrc.org
    - edge1-b2.campus4.ws.nsrc.org
    - edge1-b2.campus5.ws.nsrc.org
    - edge1-b2.campus6.ws.nsrc.org
    - edge2-b1.campus1.ws.nsrc.org
    - edge2-b1.campus2.ws.nsrc.org
    - edge2-b1.campus3.ws.nsrc.org
    - edge2-b1.campus4.ws.nsrc.org
    - edge2-b1.campus5.ws.nsrc.org
    - edge2-b1.campus6.ws.nsrc.org
    - edge2-b2.campus1.ws.nsrc.org
    - edge2-b2.campus2.ws.nsrc.org
    - edge2-b2.campus3.ws.nsrc.org
    - edge2-b2.campus4.ws.nsrc.org
    - edge2-b2.campus5.ws.nsrc.org
    - edge2-b2.campus6.ws.nsrc.org

- labels:
    module: dns_udp4_nsrc.org
  targets:
    - 1.1.1.1
    - 8.8.8.8

- labels:
    module: tls_certificate
  targets:
    - www.google.com:443
    - www.nsrc.org:443
